baseURL = "https://andreyroberto19.github.io/personal-website/"
languageCode = "en-us"
title = "Andrey Roberto"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[menu]

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  images = ["/personal-website/images/internet-narrativas.jpg"]